# Generated by Django 5.2.10 on 2026-01-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
