# Generated by Django 5.2.10 on 2026-01-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='publicar',
            new_name='publicada',
        ),
    ]
